/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.*;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author jeana
 */
public class JanPrincipal extends javax.swing.JFrame {

    private ControllerArquivoBinario<Aluno> cbAluno = new ControllerArquivoBinario();
    private ControllerArquivoBinario<Professor> cbProfessor = new ControllerArquivoBinario();
    private ControllerArquivoBinario<Diretor> cbDiretor = new ControllerArquivoBinario();

    /**
     * Creates new form JanPrincipal
     */
    public JanPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPanePrincipal = new javax.swing.JScrollPane();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneCRUD = new javax.swing.JScrollPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPaneDiretorCons = new javax.swing.JScrollPane();
        jPanelCadDiretor1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cxNomeDir = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btConsDir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btAlterarDir = new javax.swing.JButton();
        btDeletarDir = new javax.swing.JButton();
        btListarDir = new javax.swing.JButton();
        btCadDir = new javax.swing.JButton();
        cxIdDir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        limparDir = new javax.swing.JButton();
        cxCpfDir = new javax.swing.JFormattedTextField();
        jScrollPaneProfessorCons = new javax.swing.JScrollPane();
        jPanelCadDiretor2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cxNomeProfessor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btConsProfessor = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btAlterarProfessor = new javax.swing.JButton();
        btDeletarProfessor = new javax.swing.JButton();
        btListarProfessor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cxDisciplinaProfessor = new javax.swing.JTextField();
        brCadProfessor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cxIdProfessor = new javax.swing.JTextField();
        limparProfessor = new javax.swing.JButton();
        cxCpfProfessor = new javax.swing.JFormattedTextField();
        jScrollPaneAlunoCons = new javax.swing.JScrollPane();
        jPanelCadDiretor3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        cxNomeAlunoCons = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btConsAluno = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cxIdAluno = new javax.swing.JTextField();
        btAlterarAluno = new javax.swing.JButton();
        btDeletarAluno = new javax.swing.JButton();
        btListarAlunos = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        cxTurmaAlunoCons = new javax.swing.JTextField();
        btCadAluno = new javax.swing.JButton();
        limparAluno = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Iniciar = new javax.swing.JMenu();
        jMenuAbrir = new javax.swing.JMenu();
        jMenuItemAbrirDiretor = new javax.swing.JMenuItem();
        jMenuItemAbrirProfessor = new javax.swing.JMenuItem();
        jMenuItemAbrirAluno = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 153));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jScrollPanePrincipal.setBackground(new java.awt.Color(255, 102, 102));

        jPanelPrincipal.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GERENCIADOR  ESCOLA UNITED");
        jPanelPrincipal.add(jLabel1);

        jScrollPanePrincipal.setViewportView(jPanelPrincipal);

        jTabbedPane1.addTab("Principal", jScrollPanePrincipal);

        jLabel7.setText("CONSULTA DE DIRETOR");

        cxNomeDir.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Nome");

        btConsDir.setText("Consultar");
        btConsDir.setToolTipText("Consulta em função do ID");
        btConsDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsDirActionPerformed(evt);
            }
        });

        jLabel14.setText("CPF");

        btAlterarDir.setText("Alterar");
        btAlterarDir.setToolTipText("Altera todo o Objeto e Procura pelo ID");
        btAlterarDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarDirActionPerformed(evt);
            }
        });

        btDeletarDir.setText("Deletar");
        btDeletarDir.setToolTipText("Deleta pelo ID");
        btDeletarDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarDirActionPerformed(evt);
            }
        });

        btListarDir.setText("Listar Diretores");
        btListarDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarDirActionPerformed(evt);
            }
        });

        btCadDir.setText("Cadastrar");
        btCadDir.setToolTipText("O ID é gerado automaticamente");
        btCadDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadDirActionPerformed(evt);
            }
        });

        cxIdDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxIdDirActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        limparDir.setText("Limpar");
        limparDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparDirActionPerformed(evt);
            }
        });

        try {
            cxCpfDir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanelCadDiretor1Layout = new javax.swing.GroupLayout(jPanelCadDiretor1);
        jPanelCadDiretor1.setLayout(jPanelCadDiretor1Layout);
        jPanelCadDiretor1Layout.setHorizontalGroup(
            jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel7)
                .addContainerGap(563, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadDiretor1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                        .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(19, 19, 19)
                        .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxNomeDir, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(cxCpfDir))
                        .addContainerGap(618, Short.MAX_VALUE))
                    .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btListarDir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCadDir)
                        .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(limparDir, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadDiretor1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(34, 34, 34)
                                        .addComponent(cxIdDir, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(btConsDir)
                                .addGap(18, 18, 18)
                                .addComponent(btAlterarDir)
                                .addGap(32, 32, 32)
                                .addComponent(btDeletarDir)))
                        .addGap(154, 154, 154))))
        );
        jPanelCadDiretor1Layout.setVerticalGroup(
            jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addGap(118, 118, 118)
                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cxNomeDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cxCpfDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btCadDir)
                        .addComponent(btListarDir))
                    .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                        .addComponent(limparDir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxIdDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btConsDir)
                            .addComponent(btAlterarDir)
                            .addComponent(btDeletarDir))))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jScrollPaneDiretorCons.setViewportView(jPanelCadDiretor1);

        jTabbedPane2.addTab("Diretor", jScrollPaneDiretorCons);

        jLabel15.setText("CONSULTA DE PROFESSOR");

        cxNomeProfessor.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel16.setText("Nome");

        btConsProfessor.setText("Consultar");
        btConsProfessor.setToolTipText("Consulta em função do ID");
        btConsProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsProfessorActionPerformed(evt);
            }
        });

        jLabel17.setText("CPF");

        btAlterarProfessor.setText("Alterar");
        btAlterarProfessor.setToolTipText("Altera todo o Objeto e Procura pelo ID");
        btAlterarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarProfessorActionPerformed(evt);
            }
        });

        btDeletarProfessor.setText("Deletar");
        btDeletarProfessor.setToolTipText("Deleta pelo ID");
        btDeletarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarProfessorActionPerformed(evt);
            }
        });

        btListarProfessor.setText("Listar Professores");
        btListarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarProfessorActionPerformed(evt);
            }
        });

        jLabel3.setText("Disciplina");

        brCadProfessor.setText("Cadastrar");
        brCadProfessor.setToolTipText("O ID é gerado automaticamente");
        brCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brCadProfessorActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        limparProfessor.setText("Limpar");
        limparProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparProfessorActionPerformed(evt);
            }
        });

        try {
            cxCpfProfessor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanelCadDiretor2Layout = new javax.swing.GroupLayout(jPanelCadDiretor2);
        jPanelCadDiretor2.setLayout(jPanelCadDiretor2Layout);
        jPanelCadDiretor2Layout.setHorizontalGroup(
            jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                            .addComponent(cxNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(cxDisciplinaProfessor))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadDiretor2Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(48, 48, 48)
                            .addComponent(cxCpfProfessor)))
                    .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btListarProfessor)
                        .addGap(27, 27, 27)
                        .addComponent(brCadProfessor)
                        .addGap(150, 150, 150)
                        .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cxIdProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadDiretor2Layout.createSequentialGroup()
                                    .addGap(171, 171, 171)
                                    .addComponent(limparProfessor)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadDiretor2Layout.createSequentialGroup()
                                .addComponent(btConsProfessor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAlterarProfessor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDeletarProfessor))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadDiretor2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(220, 220, 220)))
                .addGap(180, 180, 180))
        );
        jPanelCadDiretor2Layout.setVerticalGroup(
            jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel15)
                .addGap(77, 77, 77)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cxNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxDisciplinaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cxCpfProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparProfessor)
                    .addComponent(brCadProfessor)
                    .addComponent(btListarProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cxIdProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDeletarProfessor)
                    .addComponent(btAlterarProfessor)
                    .addComponent(btConsProfessor))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jScrollPaneProfessorCons.setViewportView(jPanelCadDiretor2);

        jTabbedPane2.addTab("Professor", jScrollPaneProfessorCons);

        jLabel18.setText("CONSULTA DE ALUNO");

        cxNomeAlunoCons.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel19.setText("Nome");

        btConsAluno.setText("Consultar");
        btConsAluno.setToolTipText("Consulta em função do ID");
        btConsAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsAlunoActionPerformed(evt);
            }
        });

        jLabel20.setText("ID");

        btAlterarAluno.setText("Alterar");
        btAlterarAluno.setToolTipText("Altera todo o Objeto e Procura pelo ID");
        btAlterarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarAlunoActionPerformed(evt);
            }
        });

        btDeletarAluno.setText("Deletar");
        btDeletarAluno.setToolTipText("Deleta pelo ID");
        btDeletarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarAlunoActionPerformed(evt);
            }
        });

        btListarAlunos.setText("Listar Alunos");
        btListarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarAlunosActionPerformed(evt);
            }
        });

        jLabel23.setText("Turma");

        btCadAluno.setText("Cadastrar");
        btCadAluno.setToolTipText("O ID é gerado automaticamente");
        btCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadAlunoActionPerformed(evt);
            }
        });

        limparAluno.setText("Limpar");
        limparAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadDiretor3Layout = new javax.swing.GroupLayout(jPanelCadDiretor3);
        jPanelCadDiretor3.setLayout(jPanelCadDiretor3Layout);
        jPanelCadDiretor3Layout.setHorizontalGroup(
            jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadDiretor3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(28, 28, 28)
                        .addComponent(cxNomeAlunoCons, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(27, 27, 27)
                        .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                                .addComponent(btListarAlunos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btCadAluno))
                            .addComponent(cxTurmaAlunoCons))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                        .addComponent(btConsAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterarAluno)
                        .addGap(18, 18, 18)
                        .addComponent(btDeletarAluno))
                    .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(32, 32, 32)
                        .addComponent(cxIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(limparAluno))
                .addGap(122, 122, 122))
            .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadDiretor3Layout.setVerticalGroup(
            jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel18)
                .addGap(117, 117, 117)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cxNomeAlunoCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxTurmaAlunoCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparAluno)
                    .addComponent(btListarAlunos)
                    .addComponent(btCadAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDeletarAluno)
                    .addComponent(btAlterarAluno)
                    .addComponent(btConsAluno))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jScrollPaneAlunoCons.setViewportView(jPanelCadDiretor3);

        jTabbedPane2.addTab("Aluno", jScrollPaneAlunoCons);

        jScrollPaneCRUD.setViewportView(jTabbedPane2);

        jTabbedPane1.addTab("CRUD", jScrollPaneCRUD);

        jPanel1.add(jTabbedPane1);

        getContentPane().add(jPanel1);

        Iniciar.setText("Iniciar");

        jMenuAbrir.setText("Abrir");

        jMenuItemAbrirDiretor.setText("Abrir Diretores");
        jMenuItemAbrirDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirDiretorActionPerformed(evt);
            }
        });
        jMenuAbrir.add(jMenuItemAbrirDiretor);

        jMenuItemAbrirProfessor.setText("Abrir Professores");
        jMenuItemAbrirProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirProfessorActionPerformed(evt);
            }
        });
        jMenuAbrir.add(jMenuItemAbrirProfessor);

        jMenuItemAbrirAluno.setText("Abrir Alunos");
        jMenuItemAbrirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirAlunoActionPerformed(evt);
            }
        });
        jMenuAbrir.add(jMenuItemAbrirAluno);

        Iniciar.add(jMenuAbrir);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        Iniciar.add(jMenuItemSair);

        jMenuBar1.add(Iniciar);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(999, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAbrirDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirDiretorActionPerformed
        cbDiretor.setArquivo("Abrir");
        if (cbDiretor.getArquivo() == null) { //Caso o cara cancele na hora de abrir

        } else if (cbDiretor.ler()) {
            mensagemTela(true, "Arquivo aceito!");
        } else {
            mensagemTela(false, "Error!");
        }


    }//GEN-LAST:event_jMenuItemAbrirDiretorActionPerformed

    private void jMenuItemAbrirProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirProfessorActionPerformed

        cbProfessor.setArquivo("Abrir");
        if (cbProfessor.getArquivo() == null) { //Caso o cara cancele na hora de abrir

        } else if (cbProfessor.ler()) {
            mensagemTela(true, "Arquivo aceito!");
        } else {
            mensagemTela(false, "Error!");
        }
    }//GEN-LAST:event_jMenuItemAbrirProfessorActionPerformed

    private void jMenuItemAbrirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirAlunoActionPerformed

        cbAluno.setArquivo("Abrir");
        if (cbAluno.getArquivo() == null) { //Caso o cara cancele na hora de abrir

        } else if (cbAluno.ler()) {
            mensagemTela(true, "Arquivo aceito!");
        } else {
            mensagemTela(false, "Error!");
        }
    }//GEN-LAST:event_jMenuItemAbrirAlunoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void btConsDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsDirActionPerformed
        verificacaoListaDiretor();
        if (!(cbDiretor.getLista() == null) && cbDiretor.getArquivo() != null) {
            {
                try {
                    Diretor diretor = new Diretor(Integer.parseInt(cxIdDir.getText()));
                    diretor = cbDiretor.consLista(diretor);
                    if (diretor != null) {
                        cxNomeDir.setText(diretor.getNome());
                        cxCpfDir.setText(diretor.getCpf());
                    } else {
                        mensagemTela(false, "Não encontrado!");
                        limparConsDiretor();
                    }
                } catch (NumberFormatException nfe) {
                    mensagemTela(false, "O ID precisa ser um inteiro");
                    cxIdDir.requestFocus();
                }
            }
        }

    }//GEN-LAST:event_btConsDirActionPerformed

    private void btAlterarDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarDirActionPerformed
        verificacaoListaDiretor();
        try {
            boolean parametro = (cbDiretor.updatePessoa(new Diretor(Integer.parseInt(cxIdDir.getText()), cxNomeDir.getText(), cxCpfDir.getText())));
            mensagemTela(parametro, parametro ? "Atualizado!" : "Não foi possível atualizar, verifique o ID");
            limparConsDiretor();
        } catch (NumberFormatException nfe) {
            mensagemTela(false, "O ID precisa existir!");
            cxCpfDir.requestFocus();
        }
    }//GEN-LAST:event_btAlterarDirActionPerformed

    private void btDeletarDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarDirActionPerformed
        verificacaoListaDiretor();
        try {
            if (!(cbDiretor.getLista() == null) && cbDiretor.getArquivo() != null) {
                boolean parametro = cbDiretor.deletePessoa(new Diretor(Integer.parseInt(cxIdDir.getText())));
                mensagemTela(parametro, parametro ? "Deletado!" : "A pessoa não existe!");
                limparConsDiretor();
            }
        } catch (NumberFormatException nfe) {
            mensagemTela(false, "O ID precisa ser um número");
            cxIdDir.requestFocus();
        }

    }//GEN-LAST:event_btDeletarDirActionPerformed

    private void btListarDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarDirActionPerformed
        verificacaoListaDiretor();
        if (!(cbDiretor.getLista() == null) && cbDiretor.getArquivo() != null) {
            mensagemTela(true, cbDiretor.getLista().toString());
        } else {
            mensagemTela(false, "Arquivo não constatado.");
        }
    }//GEN-LAST:event_btListarDirActionPerformed

    private void btCadDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadDirActionPerformed

        if (cxNomeDir.getText().isEmpty()) {
            mensagemTela(false, "Precisa de nome!");
        } else {
            try {
                cbDiretor.getLista().add(new Diretor(cxNomeDir.getText(), cxCpfDir.getText()));
                if (cbDiretor.escrever(false)) {
                    mensagemTela(true, "Cadastrado!");
                } else {
                    jMenuItemAbrirDiretorActionPerformed(null);
                    if (JOptionPane.showConfirmDialog(this, "Gostaria de cadastrar?", "Cadastro", 1) == 0) {
                        btCadDirActionPerformed(null);
                    }
                }

            } catch (NumberFormatException nfe) {
                mensagemTela(false, "O CPF precisa ser numérico!");
                cxCpfDir.requestFocus();
            } finally {
                limparConsDiretor();
            }
        }

    }//GEN-LAST:event_btCadDirActionPerformed

    private void btConsProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsProfessorActionPerformed
        verificacaoListaProfessor();
        if (!(cbProfessor.getLista() == null) && cbProfessor.getArquivo() != null) {
            {
                try {
                    Professor professor = (new Professor(Integer.parseInt(cxIdProfessor.getText())));
                    professor = cbProfessor.consLista(professor);
                    if (professor != null) {
                        cxNomeProfessor.setText(professor.getNome());
                        cxDisciplinaProfessor.setText(professor.getDisciplina());
                        cxCpfProfessor.setText(professor.getCpf());
                    } else {
                        mensagemTela(false, "Não encontrado!");
                        limparConsProfessor();
                    }
                } catch (NumberFormatException nfe) {
                    mensagemTela(false, "O ID precisa ser um inteiro");
                    cxIdProfessor.requestFocus();
                }
            }
        }

    }//GEN-LAST:event_btConsProfessorActionPerformed

    private void btAlterarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarProfessorActionPerformed
        verificacaoListaProfessor();

        try {
            boolean parametro = cbProfessor.updatePessoa(new Professor(Integer.parseInt(cxIdProfessor.getText()), cxNomeProfessor.getText(), cxDisciplinaProfessor.getText(), cxCpfProfessor.getText()));
            mensagemTela(parametro, parametro ? "Atualizado!" : "Não foi possível atualizar, verifique o ID");
            limparConsProfessor();
        } catch (NumberFormatException nfe) {
            mensagemTela(false, "O ID precisa existir!");
            cxCpfDir.requestFocus();
        }
    }//GEN-LAST:event_btAlterarProfessorActionPerformed

    private void btDeletarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarProfessorActionPerformed
        verificacaoListaProfessor();

        try {
            if (!(cbProfessor.getLista() == null) && cbProfessor.getArquivo() != null) {
                boolean parametro = cbProfessor.deletePessoa(new Professor(Integer.parseInt(cxIdProfessor.getText())));
                mensagemTela(parametro, parametro ? "Deletado!" : "A pessoa não existe!");
                limparConsProfessor();
            }
        } catch (NumberFormatException nfe) {
            mensagemTela(false, "O ID precisa ser um número");
            cxIdProfessor.requestFocus();
        }

    }//GEN-LAST:event_btDeletarProfessorActionPerformed

    private void btListarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarProfessorActionPerformed
        verificacaoListaProfessor();

        if (!(cbProfessor.getLista() == null) && cbProfessor.getArquivo() != null) {
            mensagemTela(true, cbProfessor.getLista().toString());
        } else {
            mensagemTela(false, "Arquivo não constatado.");
        }

    }//GEN-LAST:event_btListarProfessorActionPerformed

    private void brCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brCadProfessorActionPerformed
        verificacaoListaProfessor();

        if (cxNomeProfessor.getText().isEmpty()) {
            mensagemTela(false, "Precisa de nome!");
        } else {

            cbProfessor.getLista().add(new Professor(cxNomeProfessor.getText(), cxDisciplinaProfessor.getText(), cxCpfProfessor.getText()));
            if (cbProfessor.escrever(false)) {
                mensagemTela(true, "Cadastrado!");
            } else {
                jMenuItemAbrirProfessorActionPerformed(null);
                if (JOptionPane.showConfirmDialog(this, "Gostaria de cadastrar?", "Cadastro", 1) == 0) {
                    brCadProfessorActionPerformed(null);
                }
            }

            limparConsProfessor();

        }


    }//GEN-LAST:event_brCadProfessorActionPerformed

    private void btConsAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsAlunoActionPerformed
        verificacaoListaAluno();

        if (!(cbAluno.getLista() == null) && cbAluno.getArquivo() != null) {
            {
                try {
                    Aluno aluno = new Aluno(Integer.parseInt(cxIdAluno.getText()));
                    aluno = cbAluno.consLista(aluno);
                    if (aluno != null) {
                        cxNomeAlunoCons.setText(aluno.getNome());
                        cxTurmaAlunoCons.setText(aluno.getTurma());
                        mensagemTela(true, "Aluno encontrado!");
                    } else {
                        mensagemTela(false, "Não encontrado!");
                        limparConsAluno();
                    }
                } catch (NumberFormatException nfe) {
                    mensagemTela(false, "O ID precisa ser um inteiro");
                    cxIdAluno.requestFocus();
                }
            }
        }

    }//GEN-LAST:event_btConsAlunoActionPerformed

    private void btAlterarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarAlunoActionPerformed
        verificacaoListaAluno();
        try {
            boolean parametro = (cbAluno.updatePessoa(new Aluno(Integer.parseInt(cxIdAluno.getText()), cxNomeAlunoCons.getText(), cxTurmaAlunoCons.getText())));
            mensagemTela(parametro, parametro ? "Atualizado!" : "Não foi possível atualizar, verifique o ID");
            limparConsAluno();
        } catch (NumberFormatException nfe) {
            mensagemTela(false, "O ID precisa existir ou o ID!");
            cxIdAluno.requestFocus();
        }

    }//GEN-LAST:event_btAlterarAlunoActionPerformed

    private void btDeletarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarAlunoActionPerformed
        verificacaoListaAluno();

        try {
            if (!(cbAluno.getLista() == null) && cbAluno.getArquivo() != null) {
                boolean parametro = cbAluno.deletePessoa(new Aluno(Integer.parseInt(cxIdAluno.getText())));
                mensagemTela(parametro, parametro ? "Deletado!" : "A pessoa não existe!");
                limparConsAluno();
            }
        } catch (NumberFormatException nfe) {
            mensagemTela(false, "O ID precisa ser um número");
            cxIdAluno.requestFocus();
        }
    }//GEN-LAST:event_btDeletarAlunoActionPerformed

    private void btListarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarAlunosActionPerformed
        verificacaoListaAluno();

        if (!(cbAluno.getLista() == null) && cbAluno.getArquivo() != null) {
            mensagemTela(true, cbAluno.getLista().toString());
        } else {
            mensagemTela(false, "Arquivo não constatado.");
        }
    }//GEN-LAST:event_btListarAlunosActionPerformed

    private void btCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadAlunoActionPerformed
        verificacaoListaAluno();

        if (cxNomeAlunoCons.getText().isEmpty()) {
            mensagemTela(false, "Precisa de nome!");
        } else {

            cbAluno.getLista().add(new Aluno(cxNomeAlunoCons.getText(), cxTurmaAlunoCons.getText()));//Como ele recupera o endereço de memória, posso só recuperar a lista e add.
            if (cbAluno.escrever(false)) {
                mensagemTela(true, "Cadastrado!");
            } else {
                jMenuItemAbrirAlunoActionPerformed(null);
                if (JOptionPane.showConfirmDialog(this, "Gostaria de cadastrar?", "Cadastro", 1) == 0) {
                    btCadAlunoActionPerformed(null);
                }
            }

        }
        limparConsAluno();

    }//GEN-LAST:event_btCadAlunoActionPerformed

    private void limparDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparDirActionPerformed
        limparConsDiretor();
    }//GEN-LAST:event_limparDirActionPerformed

    private void limparProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparProfessorActionPerformed
        limparConsProfessor();
    }//GEN-LAST:event_limparProfessorActionPerformed

    private void limparAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparAlunoActionPerformed
        limparConsAluno();
    }//GEN-LAST:event_limparAlunoActionPerformed

    private void cxIdDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxIdDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxIdDirActionPerformed

    public void mensagemTela(boolean confirmacao, String mensagem) {
        if (confirmacao) {
            JOptionPane.showMessageDialog(null, mensagem, "Confirmacao", 1);
        } else {
            JOptionPane.showMessageDialog(null, mensagem, "ERROR", 0);
        }
    }

    public void verificacaoListaAluno() {

        if (cbAluno.getArquivo() == null) {
            jMenuItemAbrirAlunoActionPerformed(null);
        }

    }

    public void verificacaoListaProfessor() {
        if (cbProfessor.getArquivo() == null) {
            jMenuItemAbrirProfessorActionPerformed(null);
        }

    }

    public void verificacaoListaDiretor() {
        if (cbDiretor.getArquivo() == null) {
            jMenuItemAbrirDiretorActionPerformed(null);
        }

    }

    public void limparConsAluno() {
        cxNomeAlunoCons.setText("");
        cxTurmaAlunoCons.setText("");
        cxIdAluno.setText("");
    }

    public void limparConsProfessor() {
        cxNomeProfessor.setText("");
        cxCpfProfessor.setText("");
        cxDisciplinaProfessor.setText("");
        cxIdProfessor.setText("");
    }

    public void limparConsDiretor() {
        cxNomeDir.setText("");
        cxCpfDir.setText("");
        cxIdDir.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Iniciar;
    private javax.swing.JButton brCadProfessor;
    private javax.swing.JButton btAlterarAluno;
    private javax.swing.JButton btAlterarDir;
    private javax.swing.JButton btAlterarProfessor;
    private javax.swing.JButton btCadAluno;
    private javax.swing.JButton btCadDir;
    private javax.swing.JButton btConsAluno;
    private javax.swing.JButton btConsDir;
    private javax.swing.JButton btConsProfessor;
    private javax.swing.JButton btDeletarAluno;
    private javax.swing.JButton btDeletarDir;
    private javax.swing.JButton btDeletarProfessor;
    private javax.swing.JButton btListarAlunos;
    private javax.swing.JButton btListarDir;
    private javax.swing.JButton btListarProfessor;
    private javax.swing.JFormattedTextField cxCpfDir;
    private javax.swing.JFormattedTextField cxCpfProfessor;
    private javax.swing.JTextField cxDisciplinaProfessor;
    private javax.swing.JTextField cxIdAluno;
    private javax.swing.JTextField cxIdDir;
    private javax.swing.JTextField cxIdProfessor;
    private javax.swing.JTextField cxNomeAlunoCons;
    private javax.swing.JTextField cxNomeDir;
    private javax.swing.JTextField cxNomeProfessor;
    private javax.swing.JTextField cxTurmaAlunoCons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrirAluno;
    private javax.swing.JMenuItem jMenuItemAbrirDiretor;
    private javax.swing.JMenuItem jMenuItemAbrirProfessor;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadDiretor1;
    private javax.swing.JPanel jPanelCadDiretor2;
    private javax.swing.JPanel jPanelCadDiretor3;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPaneAlunoCons;
    private javax.swing.JScrollPane jScrollPaneCRUD;
    private javax.swing.JScrollPane jScrollPaneDiretorCons;
    private javax.swing.JScrollPane jScrollPanePrincipal;
    private javax.swing.JScrollPane jScrollPaneProfessorCons;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton limparAluno;
    private javax.swing.JButton limparDir;
    private javax.swing.JButton limparProfessor;
    // End of variables declaration//GEN-END:variables
}
